name: Build master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Calculate version
        run: |
          ./gradlew version | grep Version | awk '{ print $2 }'

      - name: Build and Upload Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          ./gradlew jib \
            -Djib.to.image=docker.pkg.github.com/altfatterz/jgitver-demo/jgitver-demo \
            -Djib.to.auth.username=altfatterz \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
