name: Build branch

on:
  push:
    branches-ignore:
      - master

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "First job first step"

  secon-job:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "Second job first step"